SELECT FLAVOR
FROM (
    SELECT FLAVOR, TOTAL_ORDER
    FROM FIRST_HALF 

    UNION ALL

    SELECT FLAVOR, SUM(TOTAL_ORDER) ASTOTAL_ORDER
    FROM JULY 
    GROUP BY FLAVOR
) T
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3