-- 코드를 작성해주세
select P.ITEM_ID, P.ITEM_NAME, P.RARITY
from ITEM_INFO I
JOIN ITEM_TREE T ON T.PARENT_ITEM_ID = I.ITEM_ID
JOIN ITEM_INFO P ON T.ITEM_ID = P.ITEM_ID
WHERE I.RARITY ='RARE'
ORDER BY P.ITEM_ID DESC