-- 코드를 작성해주세요
SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, 
(
    SELECT MAX(SIZE_OF_COLONY)
    FROM ECOLI_DATA
    WHERE YEAR(DIFFERENTIATION_DATE) = YEAR(A.DIFFERENTIATION_DATE)
    GROUP BY YEAR(DIFFERENTIATION_DATE)
) - SIZE_OF_COLONY AS YEAR_DEV,
ID
FROM ECOLI_DATA A
GROUP BY YEAR(DIFFERENTIATION_DATE), ID
ORDER BY YEAR, YEAR_DEV